### ISSUE TITLE
thanks - bulk insert is way faster

### ISSUE THREAD

**Issue by Laeeth** [kaleidicassociates/influxdb-dlang-wrapper#4]
however upgrading vibe broke things for us:
https://github.com/kaleidicassociates/influxdb-dlang-wrapper/commit/86f3a01312ce9a933accb6387d2b356f476865a4
and forcing dataserver to use an old version of UT (== in the dub.sdl) makes it inconsistent with influxdb.  dub never resolves the circular dependencies and so our build will never finish!  so please could we make influx use this version or fix the hack in dataserver.

auto build for influx should check it doesnt break things for us...

**Comment by atilaneves** [comment]
The vibe.d version has to be upgraded or this doesn't build under dmd 2.074. Realising that things might break for dependent packages, I made two releases - the old one depends on the old vibe.d version on purpose.

**Comment by atilaneves** [comment]
I've made the dependency specification for unit-threaded more lenient for both 0.0 and 0.2 branches/tags. Right now, for vibe 0.7 specify v0.0.x, for vibe 0.8 specify v0.2.x
